/* tslint:disable */
/* eslint-disable */
/**
 * Nova backend
 * The backend API of Nova
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BitcoinHistoryData
 */
export interface BitcoinHistoryData {
    /**
     * 
     * @type {Array<BitcoinHistoryPoint>}
     * @memberof BitcoinHistoryData
     */
    'data': Array<BitcoinHistoryPoint>;
}
/**
 * 
 * @export
 * @interface BitcoinHistoryPoint
 */
export interface BitcoinHistoryPoint {
    /**
     * 
     * @type {string}
     * @memberof BitcoinHistoryPoint
     */
    'time': string;
    /**
     * 
     * @type {number}
     * @memberof BitcoinHistoryPoint
     */
    'price': number;
    /**
     * 
     * @type {number}
     * @memberof BitcoinHistoryPoint
     */
    'volume': number;
}
/**
 * 
 * @export
 * @interface BitcoinPriceData
 */
export interface BitcoinPriceData {
    /**
     * 
     * @type {number}
     * @memberof BitcoinPriceData
     */
    'currentPrice': number;
    /**
     * 
     * @type {number}
     * @memberof BitcoinPriceData
     */
    'priceChange24h': number;
    /**
     * 
     * @type {number}
     * @memberof BitcoinPriceData
     */
    'percentChange24h': number;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const BitcoinPricePeriod = {
    _24h: '24h',
    _7d: '7d',
    _30d: '30d',
    _90d: '90d'
} as const;

export type BitcoinPricePeriod = typeof BitcoinPricePeriod[keyof typeof BitcoinPricePeriod];


/**
 * 
 * @export
 * @interface BitcoinPriceResponse
 */
export interface BitcoinPriceResponse {
    /**
     * 
     * @type {BitcoinPriceData}
     * @memberof BitcoinPriceResponse
     */
    'price': BitcoinPriceData;
    /**
     * 
     * @type {BitcoinHistoryData}
     * @memberof BitcoinPriceResponse
     */
    'history': BitcoinHistoryData;
}
/**
 * 
 * @export
 * @interface CreateGuessDto
 */
export interface CreateGuessDto {
    /**
     * 
     * @type {GuessDirection}
     * @memberof CreateGuessDto
     */
    'direction': GuessDirection;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const GuessDirection = {
    Up: 'up',
    Down: 'down'
} as const;

export type GuessDirection = typeof GuessDirection[keyof typeof GuessDirection];


/**
 * 
 * @export
 * @interface GuessResponseDto
 */
export interface GuessResponseDto {
    /**
     * The ID of the guess
     * @type {string}
     * @memberof GuessResponseDto
     */
    'guessId': string;
    /**
     * The direction of the guess
     * @type {string}
     * @memberof GuessResponseDto
     */
    'direction': GuessResponseDtoDirectionEnum;
    /**
     * The start price of the guess
     * @type {number}
     * @memberof GuessResponseDto
     */
    'startPrice': number;
    /**
     * The created at date of the guess
     * @type {string}
     * @memberof GuessResponseDto
     */
    'createdAt': string;
}

export const GuessResponseDtoDirectionEnum = {
    Up: 'up',
    Down: 'down'
} as const;

export type GuessResponseDtoDirectionEnum = typeof GuessResponseDtoDirectionEnum[keyof typeof GuessResponseDtoDirectionEnum];


/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHello(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerGetHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerGetHello(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * GuessApi - axios parameter creator
 * @export
 */
export const GuessApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a guess
         * @param {CreateGuessDto} createGuessDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerCreateGuess: async (createGuessDto: CreateGuessDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createGuessDto' is not null or undefined
            assertParamExists('guessControllerCreateGuess', 'createGuessDto', createGuessDto)
            const localVarPath = `/api/v1/guess`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createGuessDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user active guess
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerGetUserActiveGuess: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/guess/active`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user guess statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerGetUserGuessStats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/guess/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Manually trigger resolution of all pending guesses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerResolveAllGuesses: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/guess/resolve-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Resolve a guess
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerResolveGuess: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('guessControllerResolveGuess', 'id', id)
            const localVarPath = `/api/v1/guess/{id}/resolve`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GuessApi - functional programming interface
 * @export
 */
export const GuessApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GuessApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a guess
         * @param {CreateGuessDto} createGuessDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async guessControllerCreateGuess(createGuessDto: CreateGuessDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.guessControllerCreateGuess(createGuessDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GuessApi.guessControllerCreateGuess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user active guess
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async guessControllerGetUserActiveGuess(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.guessControllerGetUserActiveGuess(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GuessApi.guessControllerGetUserActiveGuess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get user guess statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async guessControllerGetUserGuessStats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.guessControllerGetUserGuessStats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GuessApi.guessControllerGetUserGuessStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Manually trigger resolution of all pending guesses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async guessControllerResolveAllGuesses(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.guessControllerResolveAllGuesses(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GuessApi.guessControllerResolveAllGuesses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Resolve a guess
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async guessControllerResolveGuess(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.guessControllerResolveGuess(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GuessApi.guessControllerResolveGuess']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GuessApi - factory interface
 * @export
 */
export const GuessApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GuessApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a guess
         * @param {CreateGuessDto} createGuessDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerCreateGuess(createGuessDto: CreateGuessDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.guessControllerCreateGuess(createGuessDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user active guess
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerGetUserActiveGuess(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.guessControllerGetUserActiveGuess(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user guess statistics
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerGetUserGuessStats(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.guessControllerGetUserGuessStats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Manually trigger resolution of all pending guesses
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerResolveAllGuesses(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.guessControllerResolveAllGuesses(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Resolve a guess
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        guessControllerResolveGuess(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.guessControllerResolveGuess(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GuessApi - object-oriented interface
 * @export
 * @class GuessApi
 * @extends {BaseAPI}
 */
export class GuessApi extends BaseAPI {
    /**
     * 
     * @summary Create a guess
     * @param {CreateGuessDto} createGuessDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuessApi
     */
    public guessControllerCreateGuess(createGuessDto: CreateGuessDto, options?: RawAxiosRequestConfig) {
        return GuessApiFp(this.configuration).guessControllerCreateGuess(createGuessDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user active guess
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuessApi
     */
    public guessControllerGetUserActiveGuess(options?: RawAxiosRequestConfig) {
        return GuessApiFp(this.configuration).guessControllerGetUserActiveGuess(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user guess statistics
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuessApi
     */
    public guessControllerGetUserGuessStats(options?: RawAxiosRequestConfig) {
        return GuessApiFp(this.configuration).guessControllerGetUserGuessStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Manually trigger resolution of all pending guesses
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuessApi
     */
    public guessControllerResolveAllGuesses(options?: RawAxiosRequestConfig) {
        return GuessApiFp(this.configuration).guessControllerResolveAllGuesses(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Resolve a guess
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GuessApi
     */
    public guessControllerResolveGuess(id: string, options?: RawAxiosRequestConfig) {
        return GuessApiFp(this.configuration).guessControllerResolveGuess(id, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PriceApi - axios parameter creator
 * @export
 */
export const PriceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Bitcoin price
         * @param {BitcoinPricePeriod} [period] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        priceControllerGetBitcoinPrice: async (period?: BitcoinPricePeriod, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/price`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PriceApi - functional programming interface
 * @export
 */
export const PriceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PriceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Bitcoin price
         * @param {BitcoinPricePeriod} [period] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async priceControllerGetBitcoinPrice(period?: BitcoinPricePeriod, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BitcoinPriceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.priceControllerGetBitcoinPrice(period, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PriceApi.priceControllerGetBitcoinPrice']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PriceApi - factory interface
 * @export
 */
export const PriceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PriceApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Bitcoin price
         * @param {BitcoinPricePeriod} [period] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        priceControllerGetBitcoinPrice(period?: BitcoinPricePeriod, options?: RawAxiosRequestConfig): AxiosPromise<BitcoinPriceResponse> {
            return localVarFp.priceControllerGetBitcoinPrice(period, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PriceApi - object-oriented interface
 * @export
 * @class PriceApi
 * @extends {BaseAPI}
 */
export class PriceApi extends BaseAPI {
    /**
     * 
     * @summary Get Bitcoin price
     * @param {BitcoinPricePeriod} [period] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PriceApi
     */
    public priceControllerGetBitcoinPrice(period?: BitcoinPricePeriod, options?: RawAxiosRequestConfig) {
        return PriceApiFp(this.configuration).priceControllerGetBitcoinPrice(period, options).then((request) => request(this.axios, this.basePath));
    }
}



